### PR TITLE
added: desktop notifications

### PR DESCRIPTION
**Pull request by hoodie**
hey there, I just added desktop notifications ( linux only so far ).
These are a `feature` only.

### CODE REVIEW

**Comment by passcod** [comment]
I'm not sure how I feel about this. I think it's a cool feature, but I don't quite think it belongs in cargo watch itself. On the other hand, if it doesn't belong there, there probably needs to be some kind of extension mechanism or customisable hooks or something, so this _can_ be implemented.

**Comment by hoodie** [comment]
You're of course right, there should be a setting like `--notify` or something in `Cargo.toml`.
Currently the only thing the user can decide is whether or not to install this feature at all with `cargo install cargo-watch --features notifications`.

**Comment by passcod** [comment]
No, I mean, I'm not sure if the feature should _at all_ be in this project. I'm thinking about it, will get back to you.

**Comment by passcod** [comment]
Current thought is that this ought to be handled by an external application that would consume cargo-watch output (through pipes), parse the stream, spit out notifications through the relevant system bus, and output everything as is. A kind of specialised `tee`, if you want.

This keeps cargo-watch strictly focused on its mission (watch your cargo project) and lets the user choose which notification tool they use on top. It could even let the user filter the output through some other tools (like dybuk) before handing it over to the notification layer.

Closing this due to the above. I'll be glad, however, to link to such a tool from the Readme, if or when it is made.

**Comment by hoodie** [comment]
That's cool

**Pull request closed without merging**
