### PR TITLE
Removed Cargo.lock

### PR DESCRIPTION
**Pull request by Detegr**
AFAIK Cargo.lock does not need to be tracked with version control and is just adding noise to commits when it changes.

### CODE REVIEW

**Comment by passcod** [comment]
AFAIK a Cargo.lock *for libraries* shouldn't be tracked, but for *applications* it should. At least that's the behaviour for dependency management lock files in other languages (think Gemfile.lock for example). Is that different for Cargo/Rust and why?

**Comment by passcod** [comment]
```irclog
[11:21:07] <passcod> In Ruby/Bundler for example, it is recommended that the Gemfile.lock be left out of version control for libraries, but checked in for applications. What's the recommendation around this for Cargo? Should the Cargo.lock always be left out?
[11:22:03] <steveklabnik> same as bundler
```

**Comment by passcod** [comment]
Here's the relevant document: http://doc.crates.io/guide.html#cargo.toml-vs-cargo.lock

**Comment by Detegr** [comment]
All right. I wasn't aware that for applications it is required/recommended. Thanks for the info!

**Pull request closed without merging**
