### PR TITLE
Update libstd usage, other random changes

### PR DESCRIPTION
**Pull request by neuschaefer**
If something looks wrong, please ask. I'll split the pull request if you want.

Tested with `rustc 1.0.0-dev (2ca6eaeda 2015-03-02)`, something might have broken in the meantime.

### CODE REVIEW

**Comment by neuschaefer** [comment]
Yep, it's failing. Some patches might still be useful, feel free to `git cherry-pick`.

**Comment by passcod** [comment]
First, thank you very much!
Second, I'll have a closer look this weekend at the latest.
Feel free to add yourself to the Cargo.toml contributors list :)

**Comment by neuschaefer** [comment]
I updated my rustc to `2ca6eaeda 2015-03-02` and it's compiling fine. I blame Travis-CI. :-)

**Comment by neuschaefer** [comment]
Okay, I did a `cargo update`, the build looks good now.

**Pull request merged**
